_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.2
            "5": 0.18.3
            "6": 4.45.1
            "8":
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
